#!/usr/bin/env python3
"""Music for FUSE RUNNER (original tunes) -> music.inc

The QL beeper (IPC 8049): a pitch value p gives a square wave of about
    f = 11458.5 / (p + 9.6) Hz      (sQLux follows the 8049 code)
so p = 11458.5 / f - 9.6. Low notes are tuned well, high notes coarser,
which is why the tunes stay between G2 and E5.
Format per note: pitch, frames (50 Hz); pitch 0 = rest.
End: 255,0 = stop, 254,0 = loop.
"""
import math

NOTE = {'C': 0, 'C#': 1, 'D': 2, 'D#': 3, 'E': 4, 'F': 5, 'F#': 6, 'G': 7,
        'G#': 8, 'A': 9, 'A#': 10, 'B': 11}


def freq(name):
    n, octv = name[:-1], int(name[-1])
    semis = NOTE[n] + 12 * (octv - 4) - 9          # relative to A4
    return 440.0 * 2 ** (semis / 12)


def pitch(name):
    if name == 'R':
        return 0
    return max(1, min(250, round(11458.5 / freq(name) - 9.6)))


def tune(notes, unit):
    """notes: 'C4:1 E4:2 R:1 ...' lengths in units of `unit` frames"""
    out = []
    for tok in notes.split():
        n, l = tok.split(':')
        out += [pitch(n), int(l) * unit]
    return out


TITLE = """
G3:1 C4:1 E4:1 G4:1 E4:1 C4:1 E4:2
F4:1 A4:1 C5:1 A4:1 G4:2 E4:2
D4:1 F4:1 A4:1 F4:1 E4:1 G4:1 C5:2
B4:1 G4:1 D4:1 B3:1 C4:4
G3:1 C4:1 E4:1 G4:1 A4:2 G4:2
F4:1 E4:1 D4:1 C4:1 D4:2 G3:2
C4:1 E4:1 G4:1 C5:1 B4:1 G4:1 A4:1 B4:1
C5:4 R:4
A3:2 C4:1 E4:1 A4:2 E4:2
G3:2 B3:1 D4:1 G4:2 D4:2
F3:2 A3:1 C4:1 F4:2 A4:2
E4:1 D4:1 C4:1 B3:1 E4:4
A3:2 C4:1 E4:1 A4:2 B4:2
C5:2 B4:1 A4:1 G4:2 E4:2
F4:1 A4:1 G4:1 F4:1 E4:1 D4:1 C4:1 B3:1
C4:2 G3:2 C4:4
"""

START = "C4:1 E4:1 G4:1 C5:3"
CLEAR = "G4:1 G4:1 G4:1 C5:2 G4:1 C5:4"
OVER = "G4:2 F4:2 E4:2 D4:2 C4:2 G3:2 C3:6"
HISCORE = "C4:1 E4:1 G4:1 C5:2 G4:1 C5:1 E5:4"


def emit(f, label, data, loop):
    data = data + ([254, 0] if loop else [255, 0])
    f.write(f"{label}:\n")
    for i in range(0, len(data), 16):
        f.write("        dc.b    " + ",".join(map(str, data[i:i + 16])) + "\n")


def main():
    with open("music.inc", "w") as f:
        f.write("; generated by music.py - do not edit by hand\n")
        emit(f, "mus_title", tune(TITLE, 9), True)
        emit(f, "mus_start", tune(START, 5), False)
        emit(f, "mus_clear", tune(CLEAR, 5), False)
        emit(f, "mus_over", tune(OVER, 9), False)
        emit(f, "mus_hisc", tune(HISCORE, 5), False)
        f.write("        even\n")


if __name__ == "__main__":
    main()
